"""Add admin role and tests table

Revision ID: fb20eeb780e4
Revises: fecbe10be6ff
Create Date: 2025-10-22 03:23:02.485188

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'fb20eeb780e4'
down_revision = 'fecbe10be6ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('exam_id', sa.INTEGER(), nullable=False),
    sa.Column('question_text', sa.TEXT(), nullable=False),
    sa.Column('question_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=20), nullable=False),
    sa.Column('question_context', sa.TEXT(), nullable=True),
    sa.Column('difficulty', sa.VARCHAR(length=20), nullable=True),
    sa.Column('marks', sa.INTEGER(), nullable=True),
    sa.Column('diagram_path', sa.VARCHAR(length=255), nullable=True),
    sa.Column('options', sqlite.JSON(), nullable=True),
    sa.Column('correct_answer', sa.VARCHAR(length=10), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
